# import required libraries
from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.4.1")

# read the configuration file
configfile: "conf/config.yaml"

include: "rules/common.smk"



if config.get("run").get("conditional_plot"):

    include: "rules/extract_conditional.smk"
    include: "rules/prepare_ld.smk"
    include: "rules/draw_plot.smk"

    rule all:
        input:
            expand(ws_path("plot_cond/{locuseq}.sentinel"), locuseq = my_lb.locuseq),

else:

    include: "rules/prepare_ld.smk"
    include: "rules/draw_plot_marginal.smk"

    rule all:
        input:
            expand(ws_path("plot/{locuseq}.sentinel"), locuseq = my_lb.locuseq),
