run:
    conditional_plot: False
    study: Interval


path_gwas: "/exchange/healthds/pQTL/results/INTERVAL/qced_sumstats/outputs/" 
genotype: "/scratch/giulia.pontali/genomics_QC_pipeline/results_scratch/bed/qc_recoded_harmonised"
header:  "conf/header_interval.txt" 
lb_file: "conf/interval_vs_believe.csv"
path_out: "results/interval_vs_believe"


options:
    show_recomb: FALSE
    extn_window: 100000
    buffer: 100000 # expanding region to compute LD
    ld_window: 99999
    ld_window_r2: 0 
    ld_measure: rsquare
    build: hg19 # hg19 for Meta, Interval, hg38 for Believe
    plab: MLOG10P
    snplab: SNPID
