path_gwas: "/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits_not_flipped_filtered/output"
genotype: "/scratch/giulia.pontali/genomics_QC_pipeline/results_scratch/bed/qc_recoded_harmonised/impute_recoded_selected_sample_filter_hq_var_new_id_alleles_"
path_rds: "/scratch/dariush.ghasemi/projects/pqtl_pipeline_finemap/results/meta_correct_sdy"
lb_file: "conf/VTN_loci.csv"
path_out: "results/VTN_loci"

options:
    show_recomb: TRUE
    extn_window: 0
    ld_measure: rsquare
    build: hg19
    plab: MLOG10P
    snplab: SNPID

run:
    conditional_plot: False
